credentials:
  usernames:
    alexszabo:
      email: aszabo@gmail.com
      failed_login_attempts: 0
      logged_in: False
      name: Alex Szabo
      password: alexszabo
    andreipopescu:
      email: apopescu@gmail.com
      failed_login_attempts: 0
      logged_in: False
      name: Andrei Popescu
      password: andreipopescu
cookie:
  expiry_days: 30
  key: cookiesignaturekey
  name: cookiename
