credentials:
  usernames:
    aszabo:
      email: aszabo@gmail.com
      failed_login_attempts: 0
      logged_in: False
      name: Alex Szabo
      password: abc123
    meminescu:
      email: meminescu@gmail.com
      failed_login_attempts: 0
      logged_in: False
      name: Mihai Eminescu
      password: def456
cookie:
  expiry_days: 30
  key: cookiesignaturekey
  name: cookiename
